### ISSUE TITLE
Adding milliseconds to ticks

### ISSUE THREAD

**Issue by vurdalakov** [jitbit/FastCache#10]
`FastCache.cs` line 270:
```
TickCountWhenToKill = Environment.TickCount64 + (long)ttl.TotalMilliseconds;
```

Should be:
```
TickCountWhenToKill = Environment.TickCount64 + (long)ttl.TotalMilliseconds * 10_000;
```

> There are 10,000 ticks in a millisecond.
https://learn.microsoft.com/en-us/dotnet/api/system.timespan.ticks

**Comment by alex-jitbit** [comment]
https://learn.microsoft.com/en-us/dotnet/api/system.environment.tickcount64?view=net-8.0
