### ISSUE TITLE
Add Callback when a value gets evicted

### ISSUE THREAD

**Issue by Raildex** [jitbit/FastCache#11]
In my case, my values are `IDisposable` and use native resources.

A callback when an item gets removed from the cache is necessary to properly cleanup the resources.

A `Action<TValue>` as a constructor argument would be great.

**Comment by GabrielMarquezMatte** [comment]
Why would you not use `KeyValuePair<TKey, TValue>` instead of the `TKey` as the argument for the EvictionCallback?

**Comment by alex-jitbit** [comment]
@GabrielMarquezMatte good question. I don't know😀 
Will change in next release
