### ISSUE TITLE
Feature request: PostEvictionCallback

### ISSUE THREAD

**Issue by ruslan528** [jitbit/FastCache#6]
In common scenarios developer want to log eviction from cache. This is an important feature to improve observability of application. I propose to add new optional parameter to constructor - delegate (see Microsoft.Extensions.Caching.Memory.PostEvictionDelegate).

**Comment by alex-jitbit** [comment]
Thanks!

Do you mean one call back for every item, or cache-global?

**Comment by ruslan528** [comment]
I think that "cache-global" implementation will be enough. That universal "PostEvictionDelegate" will receive evicted item - so we will have ability to log his key and value.

**Comment by licentia88** [comment]
+1
