### ISSUE TITLE
TickCountWhenToKill appears to be populated incorrectly 

### ISSUE THREAD

**Issue by GoldieLocks89** [jitbit/FastCache#9]
https://github.com/jitbit/FastCache/blob/2a016db71fd766a49496d927c553fafec6a152a3/FastCache/FastCache.cs#L247

Isn't there a bug here? You're adding ttl.TotalMilliseconds to the current tick count, shouldn't you be adding ttl.Ticks?

**Comment by alex-jitbit** [comment]
Nope. It's a misleading name, the thing actually holds milliseconds.

https://learn.microsoft.com/en-us/dotnet/api/system.environment.tickcount64?view=net-8.0

> *Environment.TickCount64 Property*
> Gets the number **_OF MILLISECONDS_** elapsed since the system started.
